sonar.projectKey=sonar-node-app
	sonar.projectName=Sonar Node App
	sonar.projectVersion=1.0
	sonar.sources=.
	sonar.host.url=http://localhost:9000
	sonar.login=squ_a57370b1bbada0ea59406b89c80aa73326460e51
